### ISSUE TITLE
Map won't fully show if inside a jQuery slideToggle div

### ISSUE THREAD

**Issue by ssuess** [benhuson/WP-Geo#68]
I have a map on a single post that works fine if outside a region that I am toggling (slideToggle) using jQuery, but is cut off  and not centered if inside the toggle region. A window resize will fix the map cutoff but not the centering problem. Here is what it looks like after page loads and region (Project Details) is toggled to reveal:
![screen shot 2015-03-11 at 9 27 32 pm](https://cloud.githubusercontent.com/assets/288542/6610446/b789c718-c835-11e4-91d0-5010eae00489.png)

And here is what it looks like outside that region (and what I need it to look like inside):
![screen shot 2015-03-11 at 9 31 20 pm](https://cloud.githubusercontent.com/assets/288542/6610462/00c6ba58-c836-11e4-9a03-bc138eb43b1d.png)

Any ideas how to fix this?

Thanks!

**Comment by ssuess** [comment]
I found this stackoverflow post which describes the problem exactly:

http://stackoverflow.com/questions/4064275/how-to-deal-with-google-map-inside-of-a-hidden-div-updated-picture

but I can't seem to get any of the solutions to work, I keep getting errors about "map" being undefined. I then tried to add similar code to the my_wpgeo_map_js_preoverlays function but there again I can't get it to work, I get errors about triggers or map being undefined. Any suggestions for where and how to integrate this code so that my map will display properly behind a toggled div?

Thanks!

**Comment by ssuess** [comment]
Ok, I finally solved it, with help from Florian here: https://github.com/benhuson/WP-Geo/issues/64

Putting his work together with my own (for centering), it is all working now. Here is my jQuery code in case it helps anyone:

       jQuery('#my_slider_trigger').click(function(e) {
       var map_id = window[jQuery('div.wpgeo_map').attr('id')];
        jQuery('#my_slider_div').slideToggle(400);
        jQuery('#my_slider_trigger').toggleClass('open');
        var centerofmap = map_id.getCenter(); 
        google.maps.event.trigger(map_id, 'resize'); 
        map_id.setCenter(centerofmap);
        });

**Comment by benhuson** [comment]
Thanks for posting a solution for this.

Take a look at this new function based on your code above in https://github.com/benhuson/WP-Geo/pull/69/files
You would be able to use it like this:

`
jQuery( '#my_slider_trigger' ).click( function( e ) {
	wpgeo_refreshMapContainer( jQuery( 'div.wpgeo_map' ) );
} );`

Hopefully that will make it slightly easier to trigger a map refresh when needed.

I'll commit it in the next version of the plugin.
