### ISSUE TITLE
Links to posts not displaying on mashup 

### ISSUE THREAD

**Issue by Markbraggins** [benhuson/WP-Geo#70]
Hi, 
I'm using the shortcode: [wpgeo_mashup height="550px" width="99%"]
Markers for individual posts appear on the map, and the post name is visible when you hover the mouse over the top. However, there's no link visible to click to open the post. Example is at: http://opendata-aha.net/test-mashup-of-posts-on-a-single-map/
I also reported this on teh WordPress forum: https://wordpress.org/support/topic/click-on-icon-doesn%C2%B4t-work-in-the-map?replies=6
Thanks very much for your help
Mark

**Comment by benhuson** [comment]
Hi Mark,

The issue appears to be that the markers are clickable but the tooltip is appearing under your mouse pointer so you can't click the marker.

It appears that the tooltip has extra top margin applied which is pushing it down under your cursor.

Try adding the following style to your theme's stylesheet to fix for now:

```
p#tooltip2 {
   margin-top: 0px;
}
```

I'll try to addressees this in the WP Geo styles for future releases if possible.

Ben

**Comment by Markbraggins** [comment]
Hi Ben,

Thanks very much for getting back to me. I just added the style to my stylesheet and that’s done the trick! 
Thanks very much for your help

best wishes,

Mark

**Comment by benhuson** [comment]
Added in https://github.com/benhuson/WP-Geo/commit/f1d6d0afdfbc2daebd756408a42385abddc34590
