### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by WPsitesi** [benhuson/WP-Geo#80]
Hello,
I have translated your plugin to Turkish, please add me as Translator Contributor.

Mehmet HAKAN
www.wpsitesi.com

[Turkish Language Files.zip](https://github.com/benhuson/WP-Geo/files/397198/Turkish.Language.Files.zip)

**Comment by benhuson** [comment]
Added in https://github.com/benhuson/WP-Geo/commit/3d1e1004801922c76d1045123b4ae869eeb54c23
