### ISSUE TITLE
Feed don't  work after update

### ISSUE THREAD

**Issue by mzstade** [benhuson/WP-Geo#93]
Since the last update the feed won't work anymore  when i add the geographical information to the feed with the function in the settings menu.

When it's turned off, no field to the feed, the feed works correctly.

**Comment by mzstade** [comment]
Maybe thats the problem? Can anyone help?
xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:ymaps="http://api.maps.yahoo.com/Maps/V2/AnnotatedMaps.xsd" >

This will be highlightet in the feed validator

**Comment by piwel** [comment]
The second one seems to be added by [Jetpack Geo-location module](https://github.com/Automattic/jetpack/pull/9573/files#diff-640e9829892a48fc45cf4212b6282a6dR238).

**Comment by mzstade** [comment]
Why do they a link to a yahoo api and i have to use a Key for Google Maps?

**Comment by benhuson** [comment]
Here's a PR which removes the Yahoo! namespace and makes the others filterable so you can remove them if they clash with another plugin.

See #98

**Comment by benhuson** [comment]
PR committed in https://github.com/benhuson/WP-Geo/commit/fe55152c0a2635c298f049f5bbefed2b837808a2
